2023-07-26 12:53:19.630 | ERROR    | source.services.ingest_service:create_pipeline:283 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /_ingest/pipeline/attachment (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90ea9a49a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-26 12:53:19.630 | WARNING  | source.services.ingest_service:create_pipeline:284 - Application will not work as intended without ES!
2023-07-26 12:53:19.631 | ERROR    | source.services.ingest_service:create_ingest_index:239 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /documents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90ea9a6ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-26 12:53:19.632 | WARNING  | source.services.ingest_service:create_ingest_index:240 - Unable to create ingested documents index!
2023-07-26 12:53:33.255 | ERROR    | source.services.ingest_service:create_pipeline:283 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /_ingest/pipeline/attachment (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a00157520>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-26 12:53:33.256 | WARNING  | source.services.ingest_service:create_pipeline:284 - Application will not work as intended without ES!
2023-07-26 12:53:33.257 | ERROR    | source.services.ingest_service:create_ingest_index:239 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /documents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a00157d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-26 12:53:33.257 | WARNING  | source.services.ingest_service:create_ingest_index:240 - Unable to create ingested documents index!
2023-07-26 12:53:35.403 | DEBUG    | source.middlewares.observers:dispatch:16 - request /api/ execution time 0.0065
2023-07-26 12:53:35.460 | DEBUG    | source.middlewares.observers:dispatch:16 - request /api/favicon.ico execution time 0.0037
2023-07-26 12:54:59.112 | ERROR    | source.services.ingest_service:create_pipeline:283 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /_ingest/pipeline/attachment (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7435b1f670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-26 12:54:59.112 | WARNING  | source.services.ingest_service:create_pipeline:284 - Application will not work as intended without ES!
2023-07-26 12:54:59.114 | ERROR    | source.services.ingest_service:create_ingest_index:239 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /documents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7435b1fee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-26 12:54:59.114 | WARNING  | source.services.ingest_service:create_ingest_index:240 - Unable to create ingested documents index!
2023-07-26 15:06:52.400 | ERROR    | source.services.ingest_service:create_pipeline:283 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /_ingest/pipeline/attachment (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f26b4fcb5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-26 15:06:52.401 | WARNING  | source.services.ingest_service:create_pipeline:284 - Application will not work as intended without ES!
2023-07-26 15:06:52.402 | ERROR    | source.services.ingest_service:create_ingest_index:239 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /documents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f26b4fcbe20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-26 15:06:52.402 | WARNING  | source.services.ingest_service:create_ingest_index:240 - Unable to create ingested documents index!
2023-07-26 15:07:03.553 | ERROR    | source.services.ingest_service:create_pipeline:283 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /_ingest/pipeline/attachment (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f38bb5cf5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-26 15:07:03.553 | WARNING  | source.services.ingest_service:create_pipeline:284 - Application will not work as intended without ES!
2023-07-26 15:07:03.554 | ERROR    | source.services.ingest_service:create_ingest_index:239 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /documents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f38bb5cfe50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-26 15:07:03.554 | WARNING  | source.services.ingest_service:create_ingest_index:240 - Unable to create ingested documents index!
2023-07-26 15:07:06.048 | DEBUG    | source.middlewares.observers:dispatch:16 - request /api/ execution time 0.0028
2023-07-26 15:07:06.093 | DEBUG    | source.middlewares.observers:dispatch:16 - request /api/favicon.ico execution time 0.0021
2023-07-31 16:01:50.020 | ERROR    | source.services.ingest_service:create_pipeline:283 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /_ingest/pipeline/attachment (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c19e53490>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-31 16:01:50.020 | WARNING  | source.services.ingest_service:create_pipeline:284 - Application will not work as intended without ES!
2023-07-31 16:01:50.022 | ERROR    | source.services.ingest_service:create_ingest_index:239 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /documents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c19e53d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-31 16:01:50.022 | WARNING  | source.services.ingest_service:create_ingest_index:240 - Unable to create ingested documents index!
2023-07-31 16:01:53.054 | DEBUG    | source.middlewares.observers:dispatch:16 - request / execution time 0.007
2023-07-31 16:01:53.089 | DEBUG    | source.middlewares.observers:dispatch:16 - request /favicon.ico execution time 0.0011
2023-07-31 16:01:56.521 | DEBUG    | source.middlewares.observers:dispatch:16 - request /docs execution time 0.0019
2023-07-31 16:01:57.019 | DEBUG    | source.middlewares.observers:dispatch:16 - request /docs/swagger.json execution time 0.0037
2023-07-31 16:02:01.654 | ERROR    | source.services.ingest_service:create_ingest_index:239 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /documents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c1380c5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-31 16:02:01.655 | WARNING  | source.services.ingest_service:create_ingest_index:240 - Unable to create ingested documents index!
2023-07-31 16:02:01.658 | DEBUG    | source.middlewares.observers:dispatch:16 - request /ingest/store execution time 0.0063
2023-07-31 16:02:53.142 | ERROR    | source.services.ingest_service:create_pipeline:283 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /_ingest/pipeline/attachment (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8bda12f490>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-31 16:02:53.142 | WARNING  | source.services.ingest_service:create_pipeline:284 - Application will not work as intended without ES!
2023-07-31 16:02:53.143 | ERROR    | source.services.ingest_service:create_ingest_index:239 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /documents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8bda12fd00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-31 16:02:53.143 | WARNING  | source.services.ingest_service:create_ingest_index:240 - Unable to create ingested documents index!
2023-07-31 16:02:56.374 | ERROR    | source.services.ingest_service:create_ingest_index:239 - HTTPConnectionPool(host='localhost', port=9201): Max retries exceeded with url: /documents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8bd1bec0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-31 16:02:56.374 | WARNING  | source.services.ingest_service:create_ingest_index:240 - Unable to create ingested documents index!
2023-07-31 16:02:56.377 | DEBUG    | source.middlewares.observers:dispatch:16 - request /ingest/store execution time 0.0063
